"use client";
import {useCallback,useEffect,useState} from 'react';
import {Activity,ArrowUpRight,Beaker,BookOpen,BriefcaseBusiness,Check,CheckCheck,ChevronRight,Clock3,Coins,GitBranch,ListTodo,LoaderCircle,Pause,Plus,RefreshCw,ShieldCheck,Users,X} from 'lucide-react';
import {request,label,euro,when} from './api';
import type {Row,Snapshot,Lab,Agent,Task,Entry} from './types';
import LabView from './LabView';
const pages=[['Organization',Users],['Agents',Activity],['Tasks',ListTodo],['Research',Beaker],['Journal',BookOpen],['Budgets',Coins],['Reviews',CheckCheck],['Routines',Clock3],['Strategie-lab',GitBranch]] as const;
const descriptions:Record<string,string>={Organization:'Onderzoek als organisatie. Elke rol heeft een doel, grenzen en een zichtbaar spoor.',Agents:'Vaste rollen en tijdelijke specialisten. Klik op een rol voor rechten en werk.',Tasks:'Van onderzoeksvraag naar beoordeeld resultaat. Met eigenaar, doel en budget.',Research:'Bronnen, experimenten en conclusies met hun herkomst.',Journal:'Eén geschiedenis voor onderzoek, agents, besluiten en operations.',Budgets:'Gedeelde afdelingsbudgetten. Reserveringen tellen direct mee.',Reviews:'Resultaten door een andere rol laten beoordelen.',Routines:'Serverprocessen plannen werk, ook wanneer dit venster gesloten is.','Strategie-lab':'Ontwerp strategieën, onderzoek echte marktdata en configureer je bots.'};
const departments:Record<string,string>={cio:'Coördinatie','market-intelligence':'Markt & nieuws','us-equities-analyst':'US equities','crypto-analyst':'Crypto','quant-researcher':'Quant research','portfolio-manager':'Portfolio','risk-officer':'Risk','independent-reviewer':'Independent review'};
function Status({value}:{value:unknown}){const s=label(value);return <span className={'status '+(s==='IDLE'||s==='COMPLETED'||s==='APPROVED'?'good':s==='ERROR'||s==='FAILED'||s==='REJECTED'?'bad':s==='WORKING'||s==='RUNNING'||s==='REVIEW'?'working':'neutral')}><i/>{s.replaceAll('_',' ')}</span>}
function Empty({text}:{text:string}){return <div className="empty"><span className="empty-mark">↗</span><p>{text}</p></div>}
export default function Firm({terminalUrl}:{terminalUrl:string}){
 const [page,setPage]=useState('Organization'),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[lab,setLab]=useState<Lab|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[toast,setToast]=useState(''),[detail,setDetail]=useState<Row|null>(null),[taskForm,setTaskForm]=useState(false),[query,setQuery]=useState(''),[view,setView]=useState('all');
 const refresh=useCallback(async(signal?:AbortSignal)=>{const [s,l]=await Promise.all([request<Snapshot>('/snapshot',undefined,signal),request<Lab>('/lab',undefined,signal)]);setSnapshot(s);setLab(l);setError('')},[]);
 useEffect(()=>{const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;async function poll(){try{await refresh(controller.signal)}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Verbinding verbroken')}if(!controller.signal.aborted)timer=setTimeout(poll,10000)}void poll();return()=>{controller.abort();clearTimeout(timer)}},[refresh]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),7000);return()=>clearTimeout(t)},[toast]);
 const act=async(path:string,body:unknown={},message='Opgeslagen')=>{setBusy(true);try{const result=await request<Row>(path,body);await refresh();setToast(message);return result}catch(e){setError(e instanceof Error?e.message:'Actie mislukt');return null}finally{setBusy(false)}};
 const agents=snapshot?.agents??[],tasks=snapshot?.tasks??[],journals=snapshot?.journal??[],goals=snapshot?.goals??[];
 const fixed=agents.filter(a=>!a.temporary),temporary=agents.filter(a=>a.temporary),working=agents.filter(a=>['WORKING','REVIEWING'].includes(a.status)).length;
 const choose=(name:string)=>{setPage(name);setQuery('');setView('all')};
 const filteredJournal=journals.filter(e=>(view==='all'||e.category===view)&&(!query||JSON.stringify(e).toLowerCase().includes(query.toLowerCase())));
 const filteredTasks=tasks.filter(t=>(view==='all'||t.status===view)&&(!query||[t.title,t.owner,t.id].join(' ').toLowerCase().includes(query.toLowerCase())));
 return <div className="firm-app">
 <header className="topbar"><a className="wordmark" href="/">WJP <span>yield</span><i/></a><nav aria-label="Hoofdnavigatie"><a href={terminalUrl}><Activity size={16}/>Terminal<ArrowUpRight size={13}/></a><button className="active" onClick={()=>choose('Organization')}><BriefcaseBusiness size={16}/>Firm</button></nav><span className="environment"><i/>Lokaal · paper</span><span className="avatar">WP</span></header>
 <div className="workspace"><aside><div className="rail-heading">FIRM WORKSPACE</div><nav aria-label="Firm-menu">{pages.map(([name,Icon])=><button key={name} className={page===name?'selected':''} aria-current={page===name?'page':undefined} onClick={()=>choose(name)}><Icon size={17}/><span>{name}</span>{name==='Tasks'&&tasks.filter(t=>t.status==='QUEUED').length>0?<em>{tasks.filter(t=>t.status==='QUEUED').length}</em>:null}</button>)}</nav><div className="rail-bottom"><ShieldCheck size={20}/><strong>Software bewaakt de grenzen</strong><p>Onderzoeksagents stellen voor. Vaste regels valideren.</p><span>Live uitvoering uitgeschakeld</span></div></aside>
 <main><div className="page-heading"><div><h1>{page==='Organization'?'Je onderzoeksfirma.':page}</h1><p>{descriptions[page]}</p></div><div className="heading-actions"><button className="icon-button" aria-label="Gegevens vernieuwen" disabled={busy} onClick={()=>{void refresh().catch(e=>setError(e.message))}}><RefreshCw size={17}/></button><button className="primary" disabled={busy||!snapshot} onClick={()=>setTaskForm(true)}><Plus size={16}/>Onderzoekstaak</button></div></div>
 {error?<div className="error-banner" role="alert">{error}<button aria-label="Foutmelding sluiten" onClick={()=>setError('')}><X size={16}/></button></div>:null}
 {!snapshot?<div className="loading"><LoaderCircle size={24} className="spin"/><p>Verbinding maken met je Firm…</p></div>:<>
 <div className="metrics"><div><span>Agents actief</span><strong>{working}<small> / 2</small></strong><p>{fixed.filter(a=>a.enabled).length} rollen ingeschakeld</p></div><div><span>Onderzoek in wachtrij</span><strong>{tasks.filter(t=>['QUEUED','ASSIGNED','WAITING'].includes(t.status)).length}</strong><p>{tasks.filter(t=>t.status==='REVIEW').length} klaar voor review</p></div><div><span>Tijdelijke specialisten</span><strong>{temporary.filter(a=>a.status!=='OFFLINE').length}<small> / 4</small></strong><p>Gedeelde rechten en budgetten</p></div><div><span>Gereserveerd budget</span><strong>{euro(snapshot.budgets.filter(b=>b.scope!=='organization').reduce((n,b)=>n+(b.reserved.eur||0),0))}</strong><p>AI-provider nog niet actief</p></div></div>
 {page==='Organization'?<><section className="section"><div className="section-title"><h2>Trading Organization</h2><span>8 vaste rollen · 3 delegatieniveaus</span></div><div className="owner-node"><span className="avatar">WP</span><div><strong>Willem Peters</strong><p>Owner / Board</p></div><span className="owner-line">Doelen · beleid · besluiten</span></div><div className="org-leads">{fixed.filter(a=>['cio','independent-reviewer'].includes(a.id)).map(a=><AgentNode key={a.id} agent={a} onOpen={()=>setDetail(a)}/>)}</div><div className="org-line"/><div className="department-grid">{fixed.filter(a=>!['cio','independent-reviewer'].includes(a.id)).map(a=><AgentNode key={a.id} agent={a} onOpen={()=>setDetail(a)}/>)}</div><p className="org-caption">Independent Reviewer rapporteert rechtstreeks aan de Owner / Board.</p></section><div className="two-column"><section className="section"><div className="section-title"><h2>Volgende werkzaamheden</h2><button className="text-button" onClick={()=>choose('Tasks')}>Inbox openen<ChevronRight size={15}/></button></div>{tasks.length?<div className="compact-list">{tasks.slice(0,4).map(t=><button key={t.id} onClick={()=>setDetail(t)}><div><strong>{t.title}</strong><span>{departments[t.owner]??t.owner}</span></div><Status value={t.status}/></button>)}</div>:<Empty text="Voeg je eerste onderzoeksvraag toe. Doel, eigenaar en reviewer zijn verplicht."/>}</section><section className="section"><div className="section-title"><h2>Traceerbaarheid</h2><button className="text-button" onClick={()=>choose('Journal')}>Journal openen<ChevronRight size={15}/></button></div><div className="trace-note"><BookOpen size={23}/><strong>Elke stap heeft een herkomst.</strong><p>Bronnen, taakclaims, kosten en besluiten delen één append-only geschiedenis.</p><button className="secondary" disabled={busy} onClick={()=>{void act('/journal/verify',undefined,'').then(r=>{if(r)setDetail(r)})}}>Integriteit controleren</button></div></section></div></>:null}
 {page==='Agents'?<section className="section"><div className="section-title"><h2>Medewerkers & specialisten</h2><span>{agents.length} geregistreerd</span></div><div className="agent-list">{agents.map(a=><div className="agent-row" key={a.id}><button onClick={()=>setDetail(a)}><span className="role-icon"><Users size={18}/></span><div><strong>{a.name}</strong><p>{a.department} · {a.temporary?'Tijdelijk':'Vaste rol'}</p></div></button><Status value={a.status}/><button className="secondary" disabled={busy} onClick={()=>{void act('/agents/'+a.id+'/pause',{},'Agent gepauzeerd')}}><Pause size={14}/>Pauzeren</button></div>)}</div></section>:null}
 {page==='Tasks'?<section className="section"><div className="toolbar"><input aria-label="Taken zoeken" placeholder="Zoek taak, eigenaar of ID…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Taakstatus" value={view} onChange={e=>setView(e.target.value)}><option value="all">Alle taken</option>{['QUEUED','WAITING','RUNNING','REVIEW','COMPLETED','BLOCKED','FAILED'].map(v=><option key={v}>{v}</option>)}</select></div><div className="table-wrap"><table><thead><tr><th>Taak</th><th>Eigenaar</th><th>Reviewer</th><th>Budget</th><th>Status</th></tr></thead><tbody>{filteredTasks.map(t=><tr key={t.id} onClick={()=>setDetail(t)}><td><button className="row-link" onClick={()=>setDetail(t)}>{t.title}<small>{t.id}</small></button></td><td>{departments[t.owner]??t.owner}</td><td>{departments[t.reviewer]??t.reviewer}</td><td>{euro(t.budget_eur)}</td><td><Status value={t.status}/></td></tr>)}</tbody></table></div>{!filteredTasks.length?<Empty text="Geen taken in deze selectie."/>:null}</section>:null}
 {page==='Journal'?<section className="section"><div className="toolbar"><input aria-label="Journal zoeken" placeholder="Zoek event-ID, actor, strategie of gebeurtenis…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Journal-weergave" value={view} onChange={e=>setView(e.target.value)}><option value="all">Alle journals</option>{['research','trading','agent','operations','decision'].map(v=><option key={v}>{v}</option>)}</select><button className="secondary" onClick={()=>{void act('/journal/verify',undefined,'').then(r=>{if(r)setDetail(r)})}}>Hashketen verifiëren</button></div><div className="journal-list">{filteredJournal.map(e=><button className="journal-row" key={e.journal_id} onClick={()=>setDetail(e)}><span className="journal-seq">{e.seq}</span><div><strong>{e.event_type.replaceAll('_',' ')}</strong><p>{e.actor} · {e.category}{e.event_id?' · '+e.event_id:''}</p></div><time>{when(e.timestamp)}</time><ChevronRight size={16}/></button>)}</div>{!filteredJournal.length?<Empty text="Geen Journal-entries in deze selectie."/>:null}</section>:null}
 {page==='Budgets'?<section className="section"><div className="section-title"><h2>Hard begrensde uitgaven</h2><span>Specialisten delen hun afdelingsbudget</span></div>{snapshot.budgets.map(b=><div className="budget-row" key={b.id}><div><strong>{b.scope}</strong><p>{label(b.period)}</p></div><div className="budget-track"><div className="track"><i style={{width:Math.min(100,((b.used.eur||0)+(b.reserved.eur||0))/(b.limits.eur||1)*100)+'%'}}/></div><span>{euro(b.used.eur)} gebruikt · {euro(b.reserved.eur)} gereserveerd</span></div><strong>{euro(b.limits.eur)}</strong><button className="text-button" onClick={()=>setDetail(b)}>Alle limieten<ChevronRight size={14}/></button></div>)}</section>:null}
 {page==='Research'?<><section className="section"><div className="section-title"><h2>Onderzoeksdoelen</h2></div><div className="compact-list">{goals.map(g=><button key={label(g.id)} onClick={()=>setDetail(g)}><div><strong>{label(g.title)}</strong><span>{label(g.description,'Organisatiedoel')}</span></div><ChevronRight size={16}/></button>)}</div></section><section className="section"><div className="section-title"><h2>Rapporten & conclusies</h2></div>{snapshot.reports.length?<div className="compact-list">{snapshot.reports.map(r=><button key={label(r.id)} onClick={()=>setDetail(r)}><div><strong>{label(r.title,r.id as string)}</strong><span>{label(r.actor??r.owner)} · {when(r.created_at)}</span></div><ChevronRight size={16}/></button>)}</div>:<Empty text="Onderzoeksresultaten verschijnen hier met feiten, hypothesen, tegenbewijs en bronnen."/>}</section><section className="section"><div className="section-title"><h2>Reproduceerbare organisatieproef</h2></div><p className="section-copy">Een expliciet gemarkeerde testfixture doorloopt event, delegatie, onderzoek, synthese en review. Geen echt marktsignaal en geen betaalde AI-run.</p><button className="secondary" disabled={busy} onClick={()=>{void act('/demo/acceptance',{},'Organisatieproef uitgevoerd').then(r=>{if(r)setDetail(r)})}}>Testketen uitvoeren<ArrowUpRight size={15}/></button></section></>:null}
 {page==='Reviews'?<section className="section"><div className="section-title"><h2>Onafhankelijke beoordeling</h2></div>{tasks.filter(t=>t.status==='REVIEW').map(t=><div className="review-row" key={t.id}><div><strong>{t.title}</strong><p>Reviewer: {departments[t.reviewer]??t.reviewer}</p></div><button className="secondary" onClick={()=>setDetail(t)}>Bewijs bekijken</button><button className="secondary" disabled={busy} onClick={()=>{void act('/tasks/'+t.id+'/review',{actor:'owner',decision:'reject',summary:'Owner requested rejection; manual gateway review'},'Resultaat afgewezen')}}>Afwijzen</button><button className="primary" disabled={busy} onClick={()=>{void act('/tasks/'+t.id+'/review',{actor:'owner',decision:'approve',summary:'Owner reviewed artifact through local gateway'},'Review vastgelegd')}}><Check size={14}/>Goedkeuren</button></div>)}{!tasks.some(t=>t.status==='REVIEW')?<Empty text="Er staan geen taken klaar voor beoordeling."/>:null}<p className="section-copy">Je beoordeelt hier als Owner. Softwarepromotie vraagt daarnaast reproduceerbaar bewijs.</p></section>:null}
 {page==='Routines'?<section className="section"><div className="section-title"><h2>Werkritme op de server</h2><button className="secondary" disabled={busy} onClick={()=>{void act('/scheduler/tick',{},'Scheduler gecontroleerd')}}>Nu controleren</button></div>{snapshot.routines.map(r=><div className="routine-row" key={label(r.id)}><Clock3 size={20}/><div><strong>{label(r.title)}</strong><p>Volgende ronde: {when(r.next_at)}</p></div><span>{Number(r.interval_seconds)/3600} uur</span><Status value={r.enabled?'SCHEDULED':'PAUSED'}/></div>)}<p className="section-copy">De scheduler bewaart eigenaarschap en staat in de database. Echte Codex-runs wachten op een geconfigureerde provider.</p></section>:null}
 {page==='Strategie-lab'&&lab?<LabView lab={lab} goals={goals} busy={busy} act={act} onOpen={setDetail}/>:null}
 </>}
 </main></div><footer><span><i className={error?'disconnected':'connected'}/>{error?'Verbinding vereist aandacht':'Lokale organisatie'}</span><span>Traceerbaar onderzoek · vaste risicoregels</span><span>WJP yield v0.2</span></footer>
 {toast?<div role="status" className="toast"><Check size={17}/>{toast}<button aria-label="Melding sluiten" onClick={()=>setToast('')}><X size={16}/></button></div>:null}
 {taskForm?<TaskModal agents={agents} goals={goals} busy={busy} onClose={()=>setTaskForm(false)} onSubmit={async body=>{const r=await act('/tasks',body,'Onderzoekstaak toegevoegd');if(r)setTaskForm(false)}}/>:null}
 {detail?<div className="modal-backdrop" onClick={()=>setDetail(null)}><section className="modal details" role="dialog" aria-modal="true" aria-label="Recorddetails" onClick={e=>e.stopPropagation()}><div className="modal-heading"><div><h2>{label(detail.name??detail.title??detail.event_type,'Details')}</h2><p>{label(detail.id??detail.journal_id,'Bewijs & herkomst')}</p></div><button aria-label="Details sluiten" className="icon-button" onClick={()=>setDetail(null)}><X size={19}/></button></div><Detail value={detail}/></section></div>:null}
 </div>
}
function AgentNode({agent:a,onOpen}:{agent:Agent;onOpen:()=>void}){return <button className={'agent-node '+(a.id==='independent-reviewer'?'reviewer-node':'')} onClick={onOpen}><div className="agent-node-top"><span className="role-icon">{a.id==='independent-reviewer'?<ShieldCheck size={19}/>:a.id==='cio'?<BriefcaseBusiness size={19}/>:<Users size={18}/>}</span><ChevronRight size={15}/></div><strong>{departments[a.id]??a.name}</strong><p>{a.name}</p><Status value={a.status}/></button>}
function Detail({value}:{value:Row}){return <dl className="detail-list">{Object.entries(value).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{typeof v==='object'&&v!==null?<pre>{JSON.stringify(v,null,2)}</pre>:label(v)}</dd></div>)}</dl>}
function TaskModal({agents,goals,busy,onClose,onSubmit}:{agents:Agent[];goals:Row[];busy:boolean;onClose:()=>void;onSubmit:(body:Row)=>Promise<void>}){const [form,setForm]=useState({title:'',description:'',owner:'quant-researcher',reviewer:'independent-reviewer',goal_id:label(goals[0]?.id,''),budget_eur:1,expected_output:'Feiten, hypothese, tegenbewijs, conclusie en bronverwijzingen'});return <div className="modal-backdrop"><form className="modal" role="dialog" aria-modal="true" aria-label="Onderzoekstaak toevoegen" onSubmit={e=>{e.preventDefault();void onSubmit(form)}}><div className="modal-heading"><h2>Nieuwe onderzoekstaak</h2><button type="button" className="icon-button" onClick={onClose} aria-label="Formulier sluiten"><X size={18}/></button></div><label>Onderzoeksvraag<input autoFocus required minLength={5} maxLength={200} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Context<textarea required rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Doel<select value={form.goal_id} onChange={e=>setForm({...form,goal_id:e.target.value})}>{goals.map(g=><option value={label(g.id)} key={label(g.id)}>{label(g.title)}</option>)}</select></label><div className="form-pair"><label>Eigenaar<select value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}>{agents.filter(a=>!a.temporary).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Reviewer<select value={form.reviewer} onChange={e=>setForm({...form,reviewer:e.target.value})}>{agents.filter(a=>!a.temporary&&a.id!==form.owner).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><label>Maximaal taakbudget (€)<input type="number" min="0.01" max="10" step="0.01" required value={form.budget_eur} onChange={e=>setForm({...form,budget_eur:Number(e.target.value)})}/></label><label>Verwacht resultaat<textarea required rows={2} value={form.expected_output} onChange={e=>setForm({...form,expected_output:e.target.value})}/></label><div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Annuleren</button><button className="primary" disabled={busy}>{busy?'Opslaan…':'Taak toevoegen'}</button></div></form></div>}
